# netlify.toml
[build]
  publish = "." # 或 "public", "dist" - 你的前端静态文件输出目录，如果你的项目根目录就是文件，则设为 "."
  command = "echo 'No client build command'" # 如果你的前端是纯静态文件，不涉及 npm run build, 可以这样写
  functions = "netlify/functions" # 你的 Netlify Functions 代码存放的目录

# 设置路由重写，使前端路由能正确处理 (可选，如果纯静态文件，直接访问 html 则不需要)
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200

# 设置 Netlify Functions 的生产环境域名白名单（防止 CORS 问题）
# [functions]
#   NODE_VERSION = "18" # 推荐设置 Node.js 版本

[[headers]]
  for = "/.netlify/functions/*" # 对所有函数路径应用 CORS Headers
  [headers.values]
    Access-Control-Allow-Origin = "https://honoka1.netlify.app" # 替换成你的 Netlify 站点域名
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Max-Age = "86400"

# 处理 OPTIONS 请求（CORS预检），重要！
[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
  conditions = {Method = ["OPTIONS"]}
