# netlify.toml

[build]
  publish = "."
  command = "echo 'No client build command'"
  functions = "netlify/functions"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://honoka1.netlify.app" # 确保这里是你正确的网站域名
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"

# ★★★ FIX: 添加了处理POST请求前CORS预检(OPTIONS)的规则，对后端稳定性至关重要 ★★★
[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true # 强制执行
  conditions = {Method = ["OPTIONS"]}

[[plugins]]
package = "@netlify/plugin-functions-install-core"
